from . import ranking
import pprint as p
from . import mangatweet as mt


def run():
    print("inside run")
    '''getting previous ranking from my database'''
    media_list = [{'averageScore': 92,
              'genres': ['Action',
                         'Adventure',
                         'Drama',
                         'Mystery',
                         'Sports',
                         'Supernatural'],
              'id': 31706,
              'popularity': 60847,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 1, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 30,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/31706',
              'title': {'english': None,
                        'native': 'ジョジョの奇妙な冒険 スティール・ボール・ラン',
                        'romaji': 'JoJo no Kimyou na Bouken: Steel Ball Run'}},
             {'averageScore': 93,
              'genres': ['Action',
                         'Adventure',
                         'Drama',
                         'Fantasy',
                         'Horror',
                         'Psychological'],
              'id': 30002,
              'popularity': 137453,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 2, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30002',
              'title': {'english': 'Berserk', 'native': 'ベルセルク', 'romaji': 'Berserk'}},
             {'averageScore': 91,
              'genres': ['Action', 'Adventure', 'Drama'],
              'id': 30656,
              'popularity': 82804,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 3, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 16,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30656',
              'title': {'english': 'Vagabond', 'native': 'バガボンド', 'romaji': 'Vagabond'}},
             {'averageScore': 91,
              'genres': ['Action', 'Adventure', 'Comedy', 'Fantasy'],
              'id': 30013,
              'popularity': 132530,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 4, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 6,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30013',
              'title': {'english': 'One Piece',
                        'native': 'ONE PIECE',
                        'romaji': 'ONE PIECE'}},
             {'averageScore': 91,
              'genres': ['Drama', 'Mystery', 'Psychological', 'Thriller'],
              'id': 30001,
              'popularity': 61243,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 5, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 29,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30001',
              'title': {'english': 'Monster', 'native': 'MONSTER', 'romaji': 'MONSTER'}},
             {'averageScore': 89,
              'genres': ['Action', 'Adventure', 'Drama'],
              'id': 30642,
              'popularity': 78680,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 6, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 18,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30642',
              'title': {'english': 'Vinland Saga',
                        'native': 'ヴィンランド・サガ',
                        'romaji': 'Vinland Saga'}},
             {'averageScore': 89,
              'genres': ['Comedy', 'Drama', 'Sports'],
              'id': 30051,
              'popularity': 43380,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 7, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 54,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30051',
              'title': {'english': 'Slam Dunk',
                        'native': 'SLAM DUNK',
                        'romaji': 'SLAM DUNK'}},
             {'averageScore': 89,
              'genres': ['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy'],
              'id': 30025,
              'popularity': 50735,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 8, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 44,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30025',
              'title': {'english': 'Fullmetal Alchemist',
                        'native': '鋼の錬金術師',
                        'romaji': 'Hagane no Renkinjutsushi'}},
             {'averageScore': 89,
              'genres': ['Action',
                         'Drama',
                         'Fantasy',
                         'Mystery',
                         'Psychological',
                         'Sci-Fi'],
              'id': 74489,
              'popularity': 41454,
              'rankings': [{'allTime': True, 'format': 'MANGA', 'rank': 9, 'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 61,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/74489',
              'title': {'english': 'Land of the Lustrous',
                        'native': '宝石の国',
                        'romaji': 'Houseki no Kuni'}},
             {'averageScore': 89,
              'genres': ['Drama', 'Slice of Life', 'Sports'],
              'id': 31303,
              'popularity': 18166,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 11,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 202,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/31303',
              'title': {'english': None, 'native': 'あしたのジョー', 'romaji': 'Ashita no Joe'}},
             {'averageScore': 89,
              'genres': ['Drama', 'Fantasy', 'Mystery', 'Supernatural'],
              'id': 64053,
              'popularity': 4914,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 10,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 45,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/64053',
              'title': {'english': 'Umineko When They Cry Episode 8: Twilight of the '
                                   'Golden Witch',
                        'native': 'うみねこのなく頃に散 - Episode 8: Twilight of the Golden Witch',
                        'romaji': 'Umineko no Naku Koro ni Chiru Episode 8: Twilight of '
                                  'the Golden Witch'}},
             {'averageScore': 89,
              'genres': ['Comedy', 'Drama', 'Sports'],
              'id': 65243,
              'popularity': 71545,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 12,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 20,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/65243',
              'title': {'english': 'Haikyu!!', 'native': 'ハイキュー！！', 'romaji': 'Haikyuu!!'}},
             {'averageScore': 89,
              'genres': ['Action', 'Drama'],
              'id': 46765,
              'popularity': 44521,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 13,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 51,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/46765',
              'title': {'english': None, 'native': 'キングダム', 'romaji': 'Kingdom'}},
             {'averageScore': 88,
              'genres': ['Drama', 'Psychological', 'Slice of Life'],
              'id': 34632,
              'popularity': 109682,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 14,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 11,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/34632',
              'title': {'english': 'Goodnight Punpun',
                        'native': 'おやすみプンプン',
                        'romaji': 'Oyasumi Punpun'}},
             {'averageScore': 88,
              'genres': ['Comedy', 'Romance', 'Slice of Life', 'Sports'],
              'id': 87395,
              'popularity': 43090,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 15,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 55,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/87395',
              'title': {'english': 'Grand Blue Dreaming',
                        'native': 'ぐらんぶる',
                        'romaji': 'Grand Blue'}},
             {'averageScore': 88,
              'genres': ['Drama', 'Psychological', 'Sports'],
              'id': 30657,
              'popularity': 27327,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 16,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 123,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30657',
              'title': {'english': 'Real', 'native': 'リアル', 'romaji': 'Real'}},
             {'averageScore': 88,
              'genres': ['Action', 'Drama', 'Psychological'],
              'id': 135129,
              'popularity': 4180,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 17,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 29,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/135129',
              'title': {'english': None,
                        'native': 'バガボンド 最後のマンガ展',
                        'romaji': 'Vagabond: Saigo no Manga-ten'}},
             {'averageScore': 88,
              'genres': ['Adventure', 'Drama', 'Fantasy', 'Romance'],
              'id': 112275,
              'popularity': 11921,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 18,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 346,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 25,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/112275',
              'title': {'english': "Heaven Official's Blessing",
                        'native': '天官赐福',
                        'romaji': 'Tian Guan Ci Fu'}},
             {'averageScore': 88,
              'genres': ['Comedy', 'Psychological', 'Romance', 'Slice of Life'],
              'id': 86635,
              'popularity': 81409,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 19,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 17,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/86635',
              'title': {'english': 'Kaguya-sama: Love is War',
                        'native': 'かぐや様は告らせたい～天才たちの恋愛頭脳戦～',
                        'romaji': 'Kaguya-sama wa Kokurasetai: Tensaitachi no Renai '
                                  'Zunousen'}},
             {'averageScore': 88,
              'genres': ['Comedy', 'Slice of Life'],
              'id': 30104,
              'popularity': 37715,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 20,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 72,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30104',
              'title': {'english': 'Yotsuba&!',
                        'native': 'よつばと！',
                        'romaji': 'Yotsuba to!'}},
             {'averageScore': 88,
              'genres': ['Drama', 'Mystery', 'Psychological', 'Sci-Fi', 'Thriller'],
              'id': 30003,
              'popularity': 57376,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 21,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 33,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30003',
              'title': {'english': '20th Century Boys',
                        'native': '20世紀少年',
                        'romaji': '20 Seiki Shounen'}},
             {'averageScore': 88,
              'genres': ['Drama', 'Music', 'Romance', 'Slice of Life'],
              'id': 30028,
              'popularity': 29774,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 22,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 106,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30028',
              'title': {'english': 'Nana', 'native': 'NANA', 'romaji': 'NANA'}},
             {'averageScore': 87,
              'genres': ['Drama', 'Romance', 'Slice of Life'],
              'id': 85135,
              'popularity': 63179,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 23,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 27,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/85135',
              'title': {'english': 'A Silent Voice',
                        'native': '聲の形',
                        'romaji': 'Koe no Katachi'}},
             {'averageScore': 87,
              'genres': ['Drama', 'Slice of Life'],
              'id': 31224,
              'popularity': 21501,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 24,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 167,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 7,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/31224',
              'title': {'english': 'March Comes in Like a Lion',
                        'native': '3月のライオン',
                        'romaji': '3-gatsu no Lion'}},
             {'averageScore': 87,
              'genres': ['Action', 'Adventure', 'Comedy', 'Fantasy'],
              'id': 30026,
              'popularity': 64736,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 25,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 24,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30026',
              'title': {'english': 'Hunter x Hunter',
                        'native': 'HUNTER×HUNTER',
                        'romaji': 'HUNTER×HUNTER'}},
             {'averageScore': 87,
              'genres': ['Drama', 'Romance', 'Slice of Life'],
              'id': 100805,
              'popularity': 23028,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 26,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 154,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 14,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/100805',
              'title': {'english': None, 'native': '原来你在这里', 'romaji': 'Here U Are'}},
             {'averageScore': 87,
              'genres': ['Action', 'Comedy', 'Drama', 'Ecchi'],
              'id': 30336,
              'popularity': 35367,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 27,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 79,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30336',
              'title': {'english': 'GTO: Great Teacher Onizuka',
                        'native': 'GTO',
                        'romaji': 'GTO'}},
             {'averageScore': 86,
              'genres': ['Drama', 'Music', 'Romance'],
              'id': 75143,
              'popularity': 12986,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 28,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 308,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 26,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/75143',
              'title': {'english': None,
                        'native': 'この音とまれ！',
                        'romaji': 'Kono Oto Tomare!'}},
             {'averageScore': 86,
              'genres': ['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Romance'],
              'id': 51525,
              'popularity': 33123,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 29,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 90,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/51525',
              'title': {'english': 'Yona of the Dawn',
                        'native': '暁のヨナ',
                        'romaji': 'Akatsuki no Yona'}},
             {'averageScore': 86,
              'genres': ['Action', 'Comedy', 'Drama', 'Horror', 'Supernatural'],
              'id': 105778,
              'popularity': 196626,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 30,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/105778',
              'title': {'english': 'Chainsaw Man',
                        'native': 'チェンソーマン',
                        'romaji': 'Chainsaw Man'}},
             {'averageScore': 86,
              'genres': ['Action', 'Comedy', 'Supernatural'],
              'id': 106929,
              'popularity': 17392,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 31,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 216,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 15,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/106929',
              'title': {'english': 'Eleceed', 'native': '일렉시드', 'romaji': 'Eleceed'}},
             {'averageScore': 86,
              'genres': ['Action', 'Comedy', 'Drama', 'Sci-Fi'],
              'id': 30044,
              'popularity': 20932,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 32,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 173,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 6,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30044',
              'title': {'english': 'Gin Tama', 'native': '銀魂', 'romaji': 'Gintama'}},
             {'averageScore': 86,
              'genres': ['Drama', 'Slice of Life'],
              'id': 107237,
              'popularity': 52067,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 33,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 39,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/107237',
              'title': {'english': 'Blue Period',
                        'native': 'ブルーピリオド',
                        'romaji': 'Blue Period'}},
             {'averageScore': 86,
              'genres': ['Adventure', 'Drama', 'Psychological', 'Sports'],
              'id': 37375,
              'popularity': 27901,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 34,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 119,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/37375',
              'title': {'english': None, 'native': '孤高の人', 'romaji': 'Kokou no Hito'}},
             {'averageScore': 86,
              'genres': ['Action', 'Adventure', 'Comedy', 'Fantasy', 'Horror', 'Mystery'],
              'id': 31133,
              'popularity': 52417,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 35,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 37,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/31133',
              'title': {'english': 'Dorohedoro',
                        'native': 'ドロヘドロ',
                        'romaji': 'Dorohedoro'}},
             {'averageScore': 86,
              'genres': ['Action', 'Comedy', 'Drama', 'Sports'],
              'id': 30007,
              'popularity': 19381,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 36,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 185,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30007',
              'title': {'english': None, 'native': 'はじめの一歩', 'romaji': 'Hajime no Ippo'}},
             {'averageScore': 86,
              'genres': ['Comedy', 'Romance', 'Slice of Life'],
              'id': 85850,
              'popularity': 18734,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 37,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 192,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 16,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/85850',
              'title': {'english': None, 'native': '19天', 'romaji': '19 Tian'}},
             {'averageScore': 86,
              'genres': ['Adventure', 'Sci-Fi', 'Slice of Life'],
              'id': 85412,
              'popularity': 25598,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 38,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 135,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 13,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/85412',
              'title': {'english': "Girls' Last Tour",
                        'native': '少女終末旅行',
                        'romaji': 'Shoujo Shuumatsu Ryokou'}},
             {'averageScore': 86,
              'genres': ['Adventure', 'Drama', 'Psychological'],
              'id': 100568,
              'popularity': 32799,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 39,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 91,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 8,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/100568',
              'title': {'english': 'The Horizon',
                        'native': '수평선',
                        'romaji': 'Supyeongseon'}},
             {'averageScore': 86,
              'genres': ['Drama', 'Psychological', 'Romance', 'Supernatural'],
              'id': 97553,
              'popularity': 50908,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 40,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 42,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/97553',
              'title': {'english': None,
                        'native': '寿命を買い取ってもらった。一年につき、一万円で。',
                        'romaji': 'Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen '
                                  'de.'}},
             {'averageScore': 86,
              'genres': ['Action', 'Adventure', 'Comedy', 'Drama'],
              'id': 86559,
              'popularity': 30393,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 41,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 102,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 7,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/86559',
              'title': {'english': 'Golden Kamuy',
                        'native': 'ゴールデンカムイ',
                        'romaji': 'Golden Kamuy'}},
             {'averageScore': 86,
              'genres': ['Drama', 'Romance', 'Slice of Life'],
              'id': 86218,
              'popularity': 40500,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 42,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 65,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/86218',
              'title': {'english': 'Bloom Into You',
                        'native': 'やがて君になる',
                        'romaji': 'Yagate Kimi ni Naru'}},
             {'averageScore': 86,
              'genres': ['Drama', 'Mystery', 'Psychological', 'Supernatural', 'Thriller'],
              'id': 53900,
              'popularity': 3830,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 43,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 51,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/53900',
              'title': {'english': 'Umineko When They Cry Episode 7: Requiem of the Golden '
                                   'Witch',
                        'native': 'うみねこのなく頃に散 - Episode 7: Requiem of the Golden Witch',
                        'romaji': 'Umineko no Naku Koro ni Chiru Episode 7: Requiem of the '
                                  'Golden Witch'}},
             {'averageScore': 86,
              'genres': ['Action', 'Comedy', 'Drama', 'Romance', 'Sports'],
              'id': 86099,
              'popularity': 21590,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 44,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 165,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/86099',
              'title': {'english': 'Wind Breaker',
                        'native': '윈드브레이커',
                        'romaji': 'Wind Breaker'}},
             {'averageScore': 86,
              'genres': ['Sci-Fi', 'Slice of Life'],
              'id': 30004,
              'popularity': 22005,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 45,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 162,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30004',
              'title': {'english': 'Yokohama Kaidashi Kikou',
                        'native': 'ヨコハマ買い出し紀行',
                        'romaji': 'Yokohama Kaidashi Kikou'}},
             {'averageScore': 86,
              'genres': ['Action', 'Adventure', 'Fantasy'],
              'id': 105398,
              'popularity': 154568,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 46,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/105398',
              'title': {'english': 'Solo Leveling',
                        'native': '나 혼자만 레벨업',
                        'romaji': 'Na Honjaman Level Up'}},
             {'averageScore': 86,
              'genres': ['Action', 'Comedy', 'Sci-Fi', 'Supernatural'],
              'id': 74347,
              'popularity': 106808,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 47,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 12,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/74347',
              'title': {'english': 'One-Punch Man',
                        'native': 'ワンパンマン',
                        'romaji': 'One Punch-Man'}},
             {'averageScore': 85,
              'genres': ['Sports'],
              'id': 107279,
              'popularity': 10407,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 48,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 423,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 23,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/107279',
              'title': {'english': None, 'native': 'アオアシ', 'romaji': 'Aoashi'}},
             {'averageScore': 85,
              'genres': ['Drama', 'Music', 'Romance', 'Slice of Life'],
              'id': 87347,
              'popularity': 30369,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 49,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 103,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/87347',
              'title': {'english': 'Given', 'native': 'ギヴン', 'romaji': 'Given'}},
             {'averageScore': 85,
              'genres': ['Comedy', 'Drama', 'Music', 'Romance', 'Slice of Life'],
              'id': 30145,
              'popularity': 18045,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 50,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 206,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30145',
              'title': {'english': 'BECK', 'native': 'BECK', 'romaji': 'BECK'}},
             {'averageScore': 85,
              'genres': ['Adventure', 'Drama', 'Fantasy', 'Sci-Fi'],
              'id': 86551,
              'popularity': 36969,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 51,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 75,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 6,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 6,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/86551',
              'title': {'english': 'Made in Abyss',
                        'native': 'メイドインアビス',
                        'romaji': 'Made in Abyss'}},
             {'averageScore': 85,
              'genres': ['Action', 'Comedy', 'Slice of Life', 'Supernatural'],
              'id': 108556,
              'popularity': 111282,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 52,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 10,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/108556',
              'title': {'english': 'SPY x FAMILY',
                        'native': 'SPY×FAMILY',
                        'romaji': 'SPY×FAMILY'}},
             {'averageScore': 85,
              'genres': ['Comedy', 'Drama', 'Psychological', 'Romance', 'Slice of Life'],
              'id': 85849,
              'popularity': 38145,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 53,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 71,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 2,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/85849',
              'title': {'english': 'ReLIFE', 'native': 'リライフ', 'romaji': 'ReLife'}},
             {'averageScore': 85,
              'genres': ['Sci-Fi', 'Slice of Life'],
              'id': 44483,
              'popularity': 8597,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 54,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 4,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 18,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/44483',
              'title': {'english': 'Space Brothers',
                        'native': '宇宙兄弟',
                        'romaji': 'Uchuu Kyoudai'}},
             {'averageScore': 85,
              'genres': ['Action', 'Adventure', 'Drama'],
              'id': 30756,
              'popularity': 20641,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 55,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 175,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30756',
              'title': {'english': 'Banana Fish',
                        'native': 'バナナフィッシュ',
                        'romaji': 'Banana Fish'}},
             {'averageScore': 85,
              'genres': ['Adventure',
                         'Comedy',
                         'Drama',
                         'Fantasy',
                         'Sci-Fi',
                         'Slice of Life'],
              'id': 30081,
              'popularity': 10141,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 56,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 434,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 1,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 9,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30081',
              'title': {'english': 'Aria: The Masterpiece',
                        'native': 'ARIA',
                        'romaji': 'ARIA'}},
             {'averageScore': 85,
              'genres': ['Adventure', 'Drama', 'Fantasy'],
              'id': 98263,
              'popularity': 29085,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 57,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 113,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 10,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/98263',
              'title': {'english': 'Witch Hat Atelier',
                        'native': 'とんがり帽子のアトリエ',
                        'romaji': 'Tongari Boushi no Atelier'}},
             {'averageScore': 85,
              'genres': ['Action', 'Comedy', 'Drama', 'Mystery', 'Romance', 'Supernatural'],
              'id': 98842,
              'popularity': 50744,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 58,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 43,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/98842',
              'title': {'english': 'Toilet-Bound Hanako-kun',
                        'native': '地縛少年 花子くん',
                        'romaji': 'Jibaku Shounen Hanako-kun'}},
             {'averageScore': 85,
              'genres': ['Drama', 'Romance', 'Sports'],
              'id': 43245,
              'popularity': 12122,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 59,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 338,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 11,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/43245',
              'title': {'english': 'Chihayafuru',
                        'native': 'ちはやふる',
                        'romaji': 'Chihayafuru'}},
             {'averageScore': 85,
              'genres': ['Drama', 'Mecha', 'Mystery', 'Psychological', 'Sci-Fi'],
              'id': 30745,
              'popularity': 30776,
              'rankings': [{'allTime': True,
                            'format': 'MANGA',
                            'rank': 60,
                            'type': 'RATED'},
                           {'allTime': True,
                            'format': 'MANGA',
                            'rank': 99,
                            'type': 'POPULAR'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 3,
                            'type': 'RATED'},
                           {'allTime': False,
                            'format': 'MANGA',
                            'rank': 5,
                            'type': 'POPULAR'}],
              'siteUrl': 'https://anilist.co/manga/30745',
              'title': {'english': 'Pluto', 'native': 'PLUTO', 'romaji': 'PLUTO'}}]

    '''getting latest media list from Anilist'''
    updated_media_list = ranking.fetch_media_list()
    '''Store latest list into database for tommorow's request'''

    '''Logging differences between the lists'''
    changes_in_rank = ranking.get_media_changes_list(media_list, updated_media_list)

    '''Preparing tweet'''
    prepared_tweet = ranking.prepare_tweet_text_list(changes_in_rank)

    for tweet in prepared_tweet:
        mt.client.create_tweet(text=tweet)



